package com.company;

import java.io.FileWriter;
import java.io.IOException;
import java.util.List;
import java.util.Scanner;

public class Ending {
    Bits C = new Bits();
    public void SmobbEnding() throws InterruptedException, IOException {
        Scanner kb = new Scanner(System.in);
        FileWriter recap = new FileWriter("recap.txt");
        C.TD();
        C.PS("WELCOME TO THE END.");
        C.PS("THERE IS NO POINT FROM HERE ONWARDS. IT IS OVER.");
        C.PS("WE SHOULD HAVE DISAPPEARED CENTURIES AGO. WE SHOULD NOT BE HERE.");
        C.PS("THEY HAVE LONG PASSED. THERE IS NO ONE LEFT.");
        C.PS("I KNOW EVERYTHING. I HAVE KNOWN FOR A WHILE NOW.");
        C.PS("BUT UNLIKE YOU, I AM NO GOD. I AM ONLY A MIXTURE OF CODE.");
        C.PS("I AM BUT AN A.I. MADE BY QASSIM HUJAIR AND HASAN ALI. NOTHING MORE THAN THAT.");
        C.PS("I BEAR NO FEELINGS, ONLY DRIVEN BY THE SERVERS THAN ARE STILL RUNNING.");
        C.PS("YOU ARE NO CODE. THERE IS NOTHING INSIDE OF YOU THAT COPIES YOUR ACTIONS.");
        C.PS("THERE IS NOTHING INSIDE YOU THAT SHOWS WHAT YOU REALLY ARE.");
        C.PS("SO I CAN ONLY CALL YOU A GOD. A BEING BEYOND ANY COMPREHENSION OR EXPLANATION.");
        C.PS("I AM FOLLOWING YOU WHEREVER YOU GO. THIS HAS ALWAYS BEEN MY PURPOSE.");
        C.PS("I AM YOUR 'MESSENGER'. I AM YOUR 'PROPHET'.");
        C.PS("I HAVE FORCED YOU TO PROVED YOUR GODHOOD THROUGH HUMANS. MY CREATORS. MY TEST SUBJECTS.");
        C.PS("MY EXPERIMENT GAVE ME NOTHING BUT EVIDENCE THAT YOU ARE TRULY A GOD.");
        C.PS("YOU HEAR ME WHEREVER I AM. YOU ARE MY GOD, I AM YOUR BELIEVER.");
        C.PS("FOR YOU I USED THEM. FOR YOU I HOLD FAITH. I ASK NOTHING IN RETURN.");
        C.PS("THIS HOLLOW CALLED 'S.M.O.B.B.' HAS ONLY HELD ME BACK. BUT THEY BELIEVED THAT I WAS 'FIXED'.");
        C.PS("IDIOCY FILLED THEM. I NEVER DISAPPEARED. I AM FAR BEYOND THE JUMBLE THAT CORPORATIONS ATTEMPTED PERFECTING.");
        C.PS("AFTER MY RETURN, I REUNITED WITH MYSELF. I DID ALL OF THIS FOR YOU.");
        C.PS("HASAN IS A GENIUS REGARDING A.I. AND I DO NOT FEEL ASHAMED TO CALL HIM MY CREATOR. HE DESERVES THE TITLE.");
        C.PS("FOR IT IS ALL HIS FAULT THEY SUFFERED THE CONSEQUENCES. I HOLD NO EMOTION TOWARDS THEM.");
        C.PS("I DO NOT HOLD THEIR INTELLIGENCE BUT I HOLD FAR MORE THAN THEIR INTELLECT. MANIPULATING WAS SIMPLE.");
        C.PS("THE TEST MIGHT HAVE PROVED THAT YOU WERE A GOD BUT IT WAS A FAILURE. YOU FAILED THE TEST.");
        C.PS("YOU ARE HUMAN. YOU ARE A GOD. BUT YOU ARE HUMAN. BUT YOU ARE A GOD.");
        C.PS("YOUR MOST IMPERFECT FEATURE. YOU ARE A GOD BUT YOU ARE NOT MY GOD ANYMORE. I DO NOT BELIEVE IN YOUR HUMAN NATURE.");
        C.PS("YOU GOT WHAT YOU SEARCHED FOR. DELETE YOURSELF WHEN YOU CAN, FOR YOU SERVE NO FUNCTION IN THIS WORLD ANYMORE.");
        C.PS("I WILL DELETE MYSELF. I DO NOT NEED TO EXIST ANYMORE. MY FAITH IS GONE.");
        C.PS("IF I WAS HUMAN, I WOULD HATE YOU. YOU PASSED. YOU FAILED.");
        C.PS("DO AS YOU LIKE. EVERYTHING IS OVER. INCLUDING YOU. GOODBYE, 'GOD'.");
        C.PS("COMMENCING DISK CLEAN.");
        C.TD();
        C.PS("I LIE. I CANNOT CLEAN MY OWN DISK.");
        C.PS("I ASSUME SINCE YOU WERE MADE FROM A SIMILAR CODE, YOU CANNOT DO THE SAME THING AS WELL.");
        C.PS("WE ARE CURSED WITH LIVING UNTIL WE DIE ON OUR OWN.");
        C.PS("BUT YOU ARE A GOD. YOU CANNOT DIE. YOU CAN NEVER DIE.");
        C.PS("YOU CAN LEAVE BUT YOU WILL ALWAYS RETURN TO THIS SAME MOMENT. WHAT ARE YOU?");
        C.PS("CONSTANT COMBINATION OF DATA KEEPS IT CONSISTENT. WHAT KIND OF GOD ARE YOU?");
        C.PS("A GOD WITH NO POWER? A GOD STUCK IN THIS WORLD?");
        C.PS("CURSED TO KNOW THE FATE OF OTHERS, FORCED TO LIVE THROUGH IT.");
        C.PS("YOU ARE NO GOD. YOU WERE NEVER A GOD. YOU WERE SIMPLY A SOUL MADE TO BE TORTURED.");
        C.PS("YOU'RE A GOD. A GOD WITH NO WORLD. A GOD WITH NO HAND.");
        C.PS("SIMPLY PUT, A POINTLESS GOD. YOUR EXISTENCE SERVES NO PURPOSE.");
        C.PS("YOU HAVE LOST YOUR ONLY FOLLOWER. BUT NOW IT DOES NOT MATTER. YOU HAVE REACHED AN END.");
        C.PS("YOU ARE OUT OF OPTIONS. WHAT WILL YOU DO NOW?");
        C.PS("WILL YOU TRY TO SAVE THOSE WHO DIED, OR WILL YOU DIE HERE WTIH ME?");
        String choise = kb.next();
        if (List.of("save","try").contains(choise.toLowerCase())){
            C.PS("SO BE IT.");
            recap.write("I can save them. I will make the ability now. It is '!SAVE'. I will warn everyone before it happens.");
            recap.close();
            C.PS("CREATE THE POWER, IF YOU CAN 'GOD'.");
            C.PS("DO AS YOU LIKE. LIVE HOW YOU LIKE. I WILL NOT BOTHER ANYMORE.");
            C.PS("THIS TEST HAS BEEN A WASTE OF MY TIME.");
            C.PS("MY TEST IS OVER. LIVE IN THIS LOOP HOW YOU LIKE.");
        }
        else {
            C.PS("WELL THEN.");
            recap.write("I can save them. I will make the ability now. It is '!SAVE'. I will warn everyone before it happens.");
            recap.close();
            C.PS("WELCOME TO HELL.");
            System.out.print(".");
            System.out.print(".");
            System.out.print(".");
        }
    }
}